#!/usr/bin/env bash
# Kavis — validate the compositor config with the REAL picom 12.5.
#
# WHY: picom's animation scripts (A3) are a config language of their own,
# the local container ships picom 10 which ignores the whole block, and a
# rejected config means the desktop boots with no compositor at all — no
# rounded corners, no shadows, no animations. That failure only shows up
# 40 minutes later in a VM screenshot, and it looks like "the theme
# broke", not "the config had a typo".
#
# So: fetch picom 12.5 from the Debian trixie archive (the version the
# ISO installs), run it under Xvfb against the shipped template AND
# against every config Settings can generate, and fail if it does not
# come up.
#
# Usage: tools/check-picom.sh
#   REFRESH=1     re-download even if the cache has the .debs
#   DISPLAY_NO=94 Xvfb display number
# Requirements: xvfb, curl, dpkg-deb
# Exit: 0 = every config started (PICOM-OK), 1 = at least one did not.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/kavis-picom"
MIRROR="https://deb.debian.org/debian"
TEMPLATE="iso/config/includes.chroot/etc/xdg/picom-kavis.conf"

for tool in Xvfb curl dpkg-deb; do
	command -v "$tool" >/dev/null 2>&1 || {
		echo "ERROR: $tool missing (apt: xvfb curl dpkg)" >&2
		exit 2
	}
done

# On Debian trixie (the CI container, and the ISO itself) the archive
# version IS the one we want — no download, no pinned URLs to rot.
PICOM=""
if command -v picom >/dev/null 2>&1; then
	have=$(picom --version 2>/dev/null | tr -d 'v' | cut -d. -f1)
	if [[ "$have" =~ ^[0-9]+$ ]] && [[ "$have" -ge 12 ]]; then
		PICOM=$(command -v picom)
	fi
fi

mkdir -p "$CACHE"
if [[ -z "$PICOM" ]] && { [[ ! -x "$CACHE/root/usr/bin/picom" ]] || [[ -n "${REFRESH:-}" ]]; }; then
	rm -rf "$CACHE/root"
	echo "==> fetching picom 12.5 and libconfig from $MIRROR"
	# The versions are pinned: this check is only meaningful if it runs
	# the version the ISO installs. Bump them together with trixie.
	for url in \
		"$MIRROR/pool/main/p/picom/picom_12.5-1_amd64.deb" \
		"$MIRROR/pool/main/libc/libconfig/libconfig11_1.7.3-2_amd64.deb"; do
		curl -fsSL "$url" -o "$CACHE/pkg.deb"
		dpkg-deb -x "$CACHE/pkg.deb" "$CACHE/root"
	done
	rm -f "$CACHE/pkg.deb"
fi
if [[ -z "$PICOM" ]]; then
	PICOM="$CACHE/root/usr/bin/picom"
	export LD_LIBRARY_PATH="$CACHE/root/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"
fi
echo "    $("$PICOM" --version) ($PICOM)"

TMP=$(mktemp -d)
export DISPLAY=":${DISPLAY_NO:-94}"
Xvfb "$DISPLAY" -screen 0 800x600x24 >/dev/null 2>&1 &
XVFB_PID=$!
cleanup() { kill "$XVFB_PID" 2>/dev/null || true; rm -rf "$TMP"; }
trap cleanup EXIT
for _ in $(seq 1 40); do xdpyinfo >/dev/null 2>&1 && break; sleep 0.25; done

fail=0
# picom has no --check mode: it either starts or dies. Give it two
# seconds; whatever it prints while starting is the verdict, and a
# config error makes it exit before the timeout does.
try() {
	local label="$1" conf="$2" log="$TMP/log"
	set +e
	timeout 2 "$PICOM" --backend xrender --config "$conf" >"$log" 2>&1
	local rc=$?
	set -e
	# 124 = killed by timeout, i.e. it was still running happily.
	if [[ $rc -ne 124 ]] || grep -qiE "^\[.*(FATAL|ERROR)" "$log"; then
		echo "  ✗ $label (exit $rc)"
		sed 's/^/      /' "$log"
		fail=1
	else
		echo "  ✓ $label"
	fi
}

echo "==> shipped template"
try "$TEMPLATE" "$TEMPLATE"

# Settings rewrites this file for every appearance change; a rule it
# generates has exactly the same power to kill the compositor.
SETTINGS_DEB=$(ls -1 out/packages/kavis-settings_*_amd64.deb 2>/dev/null | head -1 || true)
if [[ -n "$SETTINGS_DEB" ]]; then
	echo "==> configs generated by Settings"
	dpkg-deb -x "$SETTINGS_DEB" "$TMP/settings"
	BIN="$TMP/settings/usr/bin/kavis-settings"
	# The generator reads the installed template; KAVIS_PICOM_TEMPLATE
	# points it at the one in the source tree instead.
	export KAVIS_PICOM_TEMPLATE="$REPO_ROOT/$TEMPLATE"
	for style in slide grow fade none; do
		for edge in bottom top left right; do
			out="$TMP/gen-$style-$edge.conf"
			if ! "$BIN" --print-picom 8 100 "$style" "$edge" \
					>"$out" 2>/dev/null || [[ ! -s "$out" ]]; then
				echo "  ✗ popup=$style edge=$edge — generator produced nothing"
				fail=1
				continue
			fi
			try "popup=$style edge=$edge" "$out"
		done
	done
	# Animations off is a separate code path (the block is emptied).
	if "$BIN" --print-picom 12 0 slide bottom >"$TMP/gen-off.conf" 2>/dev/null; then
		try "animations off" "$TMP/gen-off.conf"
	fi
else
	echo "==> Settings package not built — generator not checked"
fi

echo
if [[ $fail -eq 0 ]]; then
	echo "PICOM-OK: every config started under picom 12.5"
else
	echo "PICOM-FAIL: see above"
fi
exit $fail
