#!/usr/bin/env python3
"""Generate the emoji search-name table (madde 4 fix).

Reads the curated emoji set out of packages/kavis-tools/src/emoji.vala
(the CATEGORIES block) and writes emoji_names.vala next to it: one
lowercase English name per glyph, taken from Python's bundled Unicode
database. Run ONCE when the emoji set changes; the generated file is
committed so the package build needs no Python. Turkish names can be
added later by post-editing the generated table (the picker searches
whatever string is stored).
"""

import re
import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SOURCE = REPO / "packages/kavis-tools/src/emoji.vala"
TARGET = REPO / "packages/kavis-tools/src/emoji_names.vala"

# Joiners and modifiers that carry no searchable meaning of their own.
SKIP = {0xFE0F, 0x200D, 0x20E3}


def glyph_name(glyph: str) -> str:
    words = []
    for ch in glyph:
        if ord(ch) in SKIP:
            continue
        try:
            words.append(unicodedata.name(ch).lower())
        except ValueError:
            pass
    return " ".join(words)


def main() -> int:
    text = SOURCE.read_text(encoding="utf-8")
    glyphs = []
    for chunk in re.findall(r'"([^"]+)"\s*\}', text):
        for glyph in chunk.split(" "):
            glyph = glyph.strip()
            if glyph and not glyph.isascii() and glyph not in glyphs:
                glyphs.append(glyph)
    if not glyphs:
        print("emoji.vala icinden glif okunamadi", file=sys.stderr)
        return 1

    lines = [
        "/* GENERATED by tools/gen-emoji-adlari.py — do not edit the",
        " * glyph/name pairs by hand except to ADD Turkish words to a",
        " * name (the picker matches substrings of the stored string).",
        " * Regenerate after changing the emoji set in emoji.vala. */",
        "",
        "namespace Kavis.Tools.EmojiNames {",
        "",
        "    public struct Entry {",
        "        public unowned string glyph;",
        "        public unowned string name;",
        "    }",
        "",
        "    public const Entry[] TABLE = {",
    ]
    for glyph in glyphs:
        name = glyph_name(glyph).replace('"', "")
        lines.append('        { "%s", "%s" },' % (glyph, name))
    lines += [
        "    };",
        "",
        "    public unowned string name_for (string glyph) {",
        "        foreach (unowned Entry e in TABLE) {",
        "            if (e.glyph == glyph) {",
        "                return e.name;",
        "            }",
        "        }",
        '        return "";',
        "    }",
        "}",
        "",
    ]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(glyphs)} glif -> {TARGET.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
