#!/usr/bin/env python3
"""Generate tests/ui/06-shortcuts.yaml from the shortcut catalogue.

Decision 9b: "every keybind turns into a scenario". Item 74 moved the
bindings out of the openbox hook and into
`iso/config/includes.chroot/usr/share/kavis/shortcuts.list`, which is
now the single source for the hook, for Settings > Keyboard and for
this generator — so the scenario cannot fall behind, and neither can
the list the user sees.

tools/check-keybinds.sh already presses every shortcut under Xvfb with
a stub for each command. This scenario is the other half: the same keys
in a REAL session, where a shortcut can fail for reasons Xvfb never
shows — that is exactly how the snap bug survived two green CI runs.
Where the effect is observable the step asserts it; otherwise the step
still runs and the selftest's own anomaly detection (crash, freeze, a
process dying, an unknown window) covers it.

Usage: tools/gen-keybind-scenario.py [--check]
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = (ROOT / "iso" / "config" / "includes.chroot" / "usr" / "share"
           / "kavis" / "shortcuts.list")
OUTPUT = ROOT / "tests" / "ui" / "06-shortcuts.yaml"

# openbox modifier letters → xdotool key names
MODIFIERS = {"W": "super", "C": "ctrl", "A": "alt", "S": "shift"}
NAMED_KEYS = {"period", "Escape", "Delete", "Tab", "Left", "Right",
              "Up", "Down", "Print"}

# What the selftest can observe, by catalogue id. Anything absent runs
# with `expect: ok` — the anomaly checks still apply.
EXPECTATIONS = {
    "snap-left":      "geometry nemo left-half",
    "snap-right":     "geometry nemo right-half",
    "maximize":       "geometry nemo maximized",
    "restore":        "geometry nemo on-screen",
    "start-menu":     "popup kavis-panel visible",
    "start-menu-alt": "popup kavis-panel visible",
    "run":            "popup kavis-panel visible",
    "overview":       "popup kavis-panel visible",
    "snap-menu":      "popup kavis-panel visible",
    "clipboard":      "popup kavis-panel visible",
    "emoji":          "popup kavis-panel visible",
    "files":          "window nemo visible",
    "settings":       "window kavis-settings visible",
    "task-manager":   "window kavis-taskmanager visible",
}

# Shortcuts a headless run must not press, and why. Every one of these
# takes the session somewhere the remaining steps cannot come back
# from — the v0.5-test1 run proved it the hard way: Win+L was pressed
# near the end of this scenario and every scenario after it ran behind
# a lock screen.
SKIP = {
    "lock-screen":      "locks the session for every scenario after this one",
    "security-screen":  "takes over the session",
    "close-window":     "closes the window the rest of the steps need",
    "screenshot":       "the capture bar stays open waiting for a selection",
    "screenshot-alt":   "same capture bar",
    "screenshot-quick": "writes a screenshot file on every run",
    "color-picker":     "grabs the pointer",
    "show-desktop":     "iconifies everything and nothing presses it back",
}

# A popup is already in the panel's address space, so it appears in
# milliseconds. A window shortcut has to start a cold GTK program, and
# under QEMU's TCG (no KVM) that does not fit in six seconds — the
# first CI run failed on exactly those two steps.
POPUP_TIMEOUT = 6000
WINDOW_TIMEOUT = 40000


def timeout_for(expect):
    return WINDOW_TIMEOUT if expect.startswith("window ") else POPUP_TIMEOUT


def xdotool_key(binding):
    """'W-S-c' → 'super+shift+c'; None when it cannot be expressed."""
    parts = binding.split("-")
    key = parts[-1]
    mods = []
    for part in parts[:-1]:
        if part not in MODIFIERS:
            return None
        mods.append(MODIFIERS[part])
    if key.startswith("XF86") or key in NAMED_KEYS or len(key) == 1:
        return "+".join(mods + [key])
    return None


def catalogue():
    """(id, group, key, action) for every catalogue line, in order."""
    entries = []
    for raw in CATALOG.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        fields = [f.strip() for f in line.split("|")]
        if len(fields) != 4:
            raise SystemExit(
                f"ERROR: {CATALOG.name}: expected 4 fields, got "
                f"{len(fields)}: {raw}")
        entries.append(tuple(fields))
    return entries


def scenario():
    lines = [
        "# GENERATED by tools/gen-keybind-scenario.py — do not edit.",
        "# Source: usr/share/kavis/shortcuts.list (the shortcut catalogue)",
        "#",
        "# Every Kavis shortcut, pressed in a REAL session. Xvfb cannot",
        "# prove a shortcut works (the snap bug passed there twice); the",
        "# steps without an assertion still catch crashes, freezes and a",
        "# panel that dies, through the runner's anomaly checks.",
        "name: 06-shortcuts",
        "title: Keyboard shortcuts",
        "item: 6",
        "allowed: [nemo, kavis-settings, kavis-taskmanager]",
        "steps:",
        "  - do: launch nemo --no-desktop /users/karan",
        "    expect: window nemo visible",
        "    timeout: 30000",
        "    note: a window to aim the window shortcuts at",
    ]
    for entry_id, group, key, _action in catalogue():
        if entry_id in SKIP:
            lines.append(f"  # not pressed — {entry_id}: {SKIP[entry_id]}")
            continue
        keys = xdotool_key(key)
        if keys is None:
            continue
        expect = EXPECTATIONS.get(entry_id, "ok")
        lines.append(f"  - do: key {keys}")
        lines.append(f"    expect: {expect}")
        if expect != "ok":
            lines.append(f"    timeout: {timeout_for(expect)}")
        lines.append(f"    note: {entry_id} ({group}) — {key}")
        if expect.startswith("popup"):
            # Leave the session as we found it, or the next press
            # toggles the popup shut instead of opening the next one.
            lines.append("  - do: key Escape")
            lines.append("    expect: popup kavis-panel hidden")
            lines.append("    timeout: 4000")
    lines += [
        "  - do: close window nemo",
        "    expect: window nemo absent",
        "    timeout: 8000",
        "",
    ]
    return "\n".join(lines)


def main(argv):
    text = scenario()
    if "--check" in argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print("ERROR: tests/ui/06-shortcuts.yaml is stale — run "
                  "tools/gen-keybind-scenario.py", file=sys.stderr)
            return 1
        print("shortcut scenario is up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    steps = text.count("  - do:")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({steps} steps)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
