#!/usr/bin/env python3
"""Generate tests/ui/06-shortcuts.yaml from the openbox keybind hook.

Decision 9b: "every keybind in rc.xml turns into a scenario". The hook
`iso/config/hooks/normal/0210-openbox-keybinds.hook.chroot` is the single
place the shortcuts are defined, so the scenario is generated from it and
cannot fall behind.

tools/check-keybinds.sh already presses every shortcut under Xvfb with a
stub for each command. This scenario is the other half: the same keys in
a REAL session, where a shortcut can fail for reasons Xvfb never shows —
that is exactly how the snap bug survived two green CI runs. Where the
effect is observable the step asserts it; otherwise the step still runs
and the selftest's own anomaly detection (crash, freeze, a process
dying, an unknown window) covers it.

Usage: tools/gen-keybind-scenario.py [--check]
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HOOK = ROOT / "iso" / "config" / "hooks" / "normal" / "0210-openbox-keybinds.hook.chroot"
OUTPUT = ROOT / "tests" / "ui" / "06-shortcuts.yaml"

# openbox modifier letters → xdotool key names
MODIFIERS = {"W": "super", "C": "ctrl", "A": "alt", "S": "shift"}
KEYS = {"period": "period", "Escape": "Escape", "Delete": "Delete",
        "Tab": "Tab", "Left": "Left", "Right": "Right", "Up": "Up",
        "Down": "Down", "Print": "Print"}

# What the selftest can observe for a given shortcut. Anything absent
# runs with `expect: ok` — the anomaly checks still apply.
EXPECTATIONS = {
    "W-Left":  ("geometry nemo left-half", "snap to the left half"),
    "W-Right": ("geometry nemo right-half", "snap to the right half"),
    "W-Up":    ("geometry nemo maximized", "maximize"),
    "W-Down":  ("geometry nemo on-screen", "restore"),
    "XF86Launch5": ("popup kavis-panel visible", "start menu (Super via xcape)"),
    "C-Escape":    ("popup kavis-panel visible", "start menu"),
    "W-r":         ("popup kavis-panel visible", "start menu with search"),
    "W-Tab":       ("popup kavis-panel visible", "overview"),
    "W-z":         ("popup kavis-panel visible", "snap menu"),
    "W-v":         ("popup kavis-panel visible", "clipboard history"),
    "W-period":    ("popup kavis-panel visible", "emoji picker"),
    "W-e":         ("window nemo visible", "Files"),
    "W-i":         ("window kavis-settings visible", "Settings"),
    "C-S-Escape":  ("window kavis-taskmanager visible", "Task Manager"),
}

# Shortcuts a headless test must not press: they end the session, lock
# the screen or hand the machine to a dialog the runner cannot dismiss.
SKIP = {
    "C-A-Delete",   # security screen: takes over the session
    "A-F4",         # closes the window the rest of the steps need
    "Print",        # capture UI: stays open waiting for a selection
    "A-Print",
    "C-Print",      # writes a screenshot file on every run
    "W-S-s",
    "W-S-c",        # colour picker: grabs the pointer
}


def xdotool_key(binding):
    """'W-S-c' → 'super+shift+c'; None when it cannot be expressed."""
    parts = binding.split("-")
    key = parts[-1]
    mods = []
    for part in parts[:-1]:
        if part not in MODIFIERS:
            return None
        mods.append(MODIFIERS[part])
    if key.startswith("XF86") or key in KEYS or len(key) == 1:
        return "+".join(mods + [KEYS.get(key, key)])
    return None


def bindings():
    """Keybind values the hook ADDS, in order, without duplicates.

    Only the heredocs that build the snippet count. The awk program
    above them also mentions keys (`key="A-F4"`, `key="Print"`) but it
    is matching bindings to REMOVE from the stock rc.xml, and a test
    that presses those would assert the opposite of what we want.
    """
    text = HOOK.read_text(encoding="utf-8")
    blocks = re.findall(r"cat >>? \"\$SNIPPET\" <<'?EOF2?'?\n(.*?)\nEOF2?\n",
                        text, re.S)
    seen = []
    for block in blocks:
        for match in re.finditer(r'key="([^"]+)"', block):
            value = match.group(1)
            if value not in seen:
                seen.append(value)
    return seen


def scenario():
    lines = [
        "# GENERATED by tools/gen-keybind-scenario.py — do not edit.",
        "# Source: iso/config/hooks/normal/0210-openbox-keybinds.hook.chroot",
        "#",
        "# Every Kavis shortcut, pressed in a REAL session. Xvfb cannot",
        "# prove a shortcut works (the snap bug passed there twice); the",
        "# steps without an assertion still catch crashes, freezes and a",
        "# panel that dies, through the runner's anomaly checks.",
        "name: 06-shortcuts",
        "title: Keyboard shortcuts",
        "item: 6",
        "allowed: [nemo, kavis-settings, kavis-taskmanager]",
        "steps:",
        "  - do: launch nemo --no-desktop /users/karan",
        "    expect: window nemo visible",
        "    timeout: 30000",
        "    note: a window to aim the window shortcuts at",
    ]
    for binding in bindings():
        if binding in SKIP:
            continue
        key = xdotool_key(binding)
        if key is None:
            continue
        expect, note = EXPECTATIONS.get(binding, ("ok", ""))
        lines.append(f"  - do: key {key}")
        lines.append(f"    expect: {expect}")
        if expect != "ok":
            lines.append("    timeout: 6000")
        lines.append(f"    note: {binding}" + (f" — {note}" if note else ""))
        if expect.startswith("popup"):
            # Leave the session as we found it, or the next press toggles
            # the popup shut instead of opening the next one.
            lines.append("  - do: key Escape")
            lines.append("    expect: popup kavis-panel hidden")
            lines.append("    timeout: 4000")
    lines += [
        "  - do: close window nemo",
        "    expect: window nemo absent",
        "    timeout: 8000",
        "",
    ]
    return "\n".join(lines)


def main(argv):
    text = scenario()
    if "--check" in argv:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print("ERROR: tests/ui/06-shortcuts.yaml is stale — run "
                  "tools/gen-keybind-scenario.py", file=sys.stderr)
            return 1
        print("shortcut scenario is up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    steps = text.count("  - do:")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({steps} steps)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
